### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by griffinlacek** [andreaargyle/prj-rev-bwfs-tea-cozy#4]
**Grade:** Exceeds Expectations

**Summary:** This project is great! It meets the spec and the code is clean/free of any errors. I wish I had more to review, but you've nailed it! No major areas of improvement to note, so keep up the good work!

One additional challenge would be to inspect your project in a mobile view (Chrome inspector can mimic mobile phones: https:// developers.google.com/web/tools/chrome-devtools/device- mode/ ). You’ll see it doesn’t look too bad, but maybe it’s hard to read. Think you could make this website better for mobile? Even just resized text would help, but maybe you could do a totally responsive resizing. Digging deeper into flex and media queries will help with this.

Here’s a great resource on mobile web development: https:// developer.mozilla.org/en-US/docs/Web/Guide/Mobile

**Comment by andreaargyle** [comment]
Thank you so much for the review and your notes! I fixed the "no-wrap" to "nowrap" and added a few media queries to a separate [teacozy repository](https://andreaargyle.github.io/teacozy/).

I'm working on the Capstone project now, I hope that review is as pleasant as yours!
